# Generated by Django 5.2.5 on 2025-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincredential',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('manager', 'Manager')], default='client', max_length=20),
        ),
    ]
